[feed.amperka]
start_url = "https://amperka.ru/collection/new"
link_extractor = { allow = "/product/", restrict_css = ".products" }
article_extractor = { title_css = ".product-detail__title", content_css = ".product-detail__description" }

[feed.easyelectronics]
start_url = "http://easyelectronics.ru/"
link_extractor = { restrict_css = ".entry-title" }
article_extractor = { title_css = ".entry-title", content_css = ".entry-content" }

[feed.schneidersladen]
start_url = "https://schneidersladen.de/en/new-stuff/"
link_extractor = { restrict_css = ".cms-element-product-listing .cms-listing-row" }
article_extractor = { title_css = ".product-detail-header h1", content_css = ".product-detail-description" }

[feed.thonk]
start_url = "https://www.thonk.co.uk/"
link_extractor = { allow = "/shop/",  restrict_css = ".product_tag-new-products" }
article_extractor = { title_css = ".product_title", content_css = "#tab-description" }

[feed.m5stack]
start_url = "https://shop.m5stack.com/"
link_extractor = { allow = "/products/",  restrict_css = ".product-card" }
article_extractor = { title_css = "[itemprop=name]", content_css = "[itemprop=description]" }
